name: Run Cron Jobs

on:
  schedule:
    - cron: '0 5 * * *'  # Runs at 5:00 AM UTC
    - cron: '0 0 * * *'  # Runs at midnight UTC
  workflow_dispatch:  # Allows manual execution

jobs:
  run-crons:
    runs-on: ubuntu-latest

    env:
      VERCEL_URL: ${{ secrets.VERCEL_URL }}

    steps:
      - name: Debug VERCEL_URL
        run: |
          if [ -z "$VERCEL_URL" ]; then
            echo "❌ ERROR: VERCEL_URL is empty!"
            exit 1
          else
            echo "✅ VERCEL_URL is set to: '$VERCEL_URL'"
          fi

      - name: Call /api/cron/check-in
        run: |
          curl -X GET "$VERCEL_URL/api/cron/check-in"

      - name: Call /api/cron/redeem-code
        run: |
          curl -X GET "$VERCEL_URL/api/cron/redeem-code"
